apiVersion: v1
entries:
  kudos:
  - annotations:
      category: Application
      licenses: MIT
    apiVersion: v2
    appVersion: 1.2.1
    created: "2025-08-29T13:51:34.417483507Z"
    description: The Kudos Helm chart - simplified PostgreSQL modes
    digest: 3e7262251dfaab534d9b3da9fb4c704d2d894caabe6511299fa86be08f282065
    keywords:
    - postgresql
    - kudos
    - operator
    name: kudos
    type: application
    urls:
    - https://synyx.github.io/kudos/docs/helm/kudos-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 1.2.1
    created: "2025-08-29T13:51:34.416495005Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.2
    description: The Kudos Helm chart
    digest: 654ea7905a3580328b1afdf4d7911ebc49601532b5988f3dfadf50d3b9943ce1
    name: kudos
    type: application
    urls:
    - https://synyx.github.io/kudos/docs/helm/kudos-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2025-08-29T13:51:34.413099383Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.2
    description: The Kudos Helm chart
    digest: 40c28f081437cba1ed7da0bb626346d85899932d208a0438e6a5bbad5cd6b82c
    name: kudos
    type: application
    urls:
    - https://synyx.github.io/kudos/docs/helm/kudos-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2025-08-29T13:51:34.409038211Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 12.1.2
    description: The Kudos Helm chart
    digest: 7ecdba359b66ba8a6bebb691de877264c1636ff283b83bd432bd13d67de5e369
    name: kudos
    type: application
    urls:
    - https://synyx.github.io/kudos/docs/helm/kudos-0.1.1.tgz
    version: 0.1.1
generated: "2025-08-29T13:51:34.405436142Z"
