replicaCount: 1

image:
  repository: ghcr.io/synyx/kudos:main
  pullPolicy: IfNotPresent
  tag: latest

app:
  origin: https://localhost
  db:
    user: 'kudos'
    passwordSecret: 'secret-name'
    host: ''
    port: 5432
    name: 'kudos'
    schema: 'public'
    migrate: true # TODO: Job Container

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  enabled: true
